#!/usr/bin/env bash
#
# setup-db-safe.sh — idempotent TAK Server DB bring-up for a SOURCE checkout.
#
# WHY THIS EXISTS:
#   The stock src/takserver-schemamanager/scripts/takserver-setup-db.sh assumes an
#   /opt/tak RPM/DEB layout. On a source checkout it:
#     (a) renames the live pg_hba.conf to a .backup, then FAILS to install a
#         replacement (it copies from a nonexistent /opt/tak/db-utils/), leaving the
#         cluster unable to start; and
#     (b) cannot find SchemaManager.jar.
#   Once pg_hba.conf is gone the cluster won't start, so every re-run just deadlocks
#   (Postgres down -> all psql calls fail -> mv/cp "missing operand" spam).
#   >>> DO NOT run takserver-setup-db.sh on this machine. Use this instead. <<<
#
# WHAT THIS DOES (idempotent — safe to re-run, and safe to call at boot):
#   1. Ensure pg_hba.conf exists (restore newest backup, else write a sane default).
#   2. Start the cluster and wait until it accepts connections.
#   3. Create role 'martiuser' ONLY if missing (password read from CoreConfig.xml).
#   4. Create database 'cot' ONLY if missing.
#   5. Apply schema via the built schemamanager uber jar ('upgrade' is idempotent).
#
# USAGE:  sudo ./setup-db-safe.sh
#
set -euo pipefail

PG_VERSION=15
PG_CLUSTER=main
PG_ETC="/etc/postgresql/${PG_VERSION}/${PG_CLUSTER}"
PGHBA="${PG_ETC}/pg_hba.conf"
DB_NAME=cot
DB_USER=martiuser

# --- resolve absolute script path & repo root (works from anywhere) -------------
SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
REPO_ROOT="$(dirname "$SCRIPT_PATH")"
CORECONFIG="${REPO_ROOT}/src/takserver-core/example/CoreConfig.xml"
SCHEMA_JAR="$(ls "${REPO_ROOT}"/src/takserver-schemamanager/build/libs/schemamanager-*-uber.jar 2>/dev/null | sort | tail -1)"

log() { echo -e "\n[setup-db-safe] $*"; }

# --- must be root (systemctl + sudo -u postgres) --------------------------------
if [ "$(id -u)" -ne 0 ]; then
  echo "[setup-db-safe] root required — re-running with sudo..."
  exec sudo "$SCRIPT_PATH" "$@"
fi

# --- read DB password from CoreConfig.xml so it ALWAYS matches the server -------
if [ ! -f "$CORECONFIG" ]; then
  echo "ERROR: CoreConfig.xml not found at $CORECONFIG" >&2
  echo "       Run your CoreConfig setup step first (./setup-coreconfig.sh)." >&2
  exit 1
fi
DB_PASS="$(grep -m1 '<connection' "$CORECONFIG" | sed -E 's/.*password="([^"]*)".*/\1/')"
if [ -z "$DB_PASS" ]; then
  echo "ERROR: could not read <connection password=\"...\"> from $CORECONFIG" >&2
  exit 1
fi

# --- 1. ensure pg_hba.conf exists ----------------------------------------------
if [ -f "$PGHBA" ]; then
  log "pg_hba.conf present — leaving it untouched."
else
  NEWEST_BAK="$(ls -t "${PG_ETC}"/pg_hba.conf.backup-* 2>/dev/null | head -1 || true)"
  if [ -n "${NEWEST_BAK:-}" ]; then
    log "pg_hba.conf missing — restoring from: ${NEWEST_BAK}"
    install -o postgres -g postgres -m 640 "$NEWEST_BAK" "$PGHBA"
  else
    log "pg_hba.conf missing and no backup found — writing a sane default."
    cat > "$PGHBA" <<'EOF'
# Minimal TAK-compatible pg_hba.conf (auto-generated by setup-db-safe.sh)
local   all   postgres            peer
local   all   all                 peer
host    all   all   127.0.0.1/32  scram-sha-256
host    all   all   ::1/128       scram-sha-256
EOF
    chown postgres:postgres "$PGHBA"
    chmod 640 "$PGHBA"
  fi
fi

# --- 2. start cluster & wait for readiness -------------------------------------
log "Ensuring PostgreSQL cluster ${PG_VERSION}/${PG_CLUSTER} is running..."
systemctl start "postgresql@${PG_VERSION}-${PG_CLUSTER}.service"

ready=false
for _ in $(seq 1 30); do
  if sudo -u postgres psql -AtqXc 'SELECT 1' >/dev/null 2>&1; then ready=true; break; fi
  sleep 1
done
if [ "$ready" != true ]; then
  echo "ERROR: PostgreSQL did not become ready. Check:" >&2
  echo "       sudo journalctl -u postgresql@${PG_VERSION}-${PG_CLUSTER} -n 30" >&2
  exit 1
fi
log "PostgreSQL is accepting connections."

# run psql from a neutral dir so the 'postgres' user doesn't warn on /home perms
cd /tmp

# --- 3. create martiuser if missing --------------------------------------------
if [ "$(sudo -u postgres psql -AtqXc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'")" = "1" ]; then
  log "Role '${DB_USER}' already exists — skipping creation."
else
  log "Creating role '${DB_USER}'..."
  sudo -u postgres psql -v ON_ERROR_STOP=1 -c \
    "CREATE ROLE ${DB_USER} LOGIN ENCRYPTED PASSWORD '${DB_PASS}' SUPERUSER INHERIT CREATEDB NOCREATEROLE;"
fi

# --- 4. create cot database if missing -----------------------------------------
if [ "$(sudo -u postgres psql -AtqXc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'")" = "1" ]; then
  log "Database '${DB_NAME}' already exists — skipping creation."
else
  log "Creating database '${DB_NAME}' (owner ${DB_USER})..."
  sudo -u postgres createdb --owner="${DB_USER}" "${DB_NAME}"
fi

# --- 5. apply schema (idempotent: applies only pending migrations) --------------
if [ -z "${SCHEMA_JAR:-}" ] || [ ! -f "$SCHEMA_JAR" ]; then
  echo "WARNING: schemamanager uber jar not found under src/takserver-schemamanager/build/libs/" >&2
  echo "         Build it first:  (cd \"$REPO_ROOT/src\" && ./gradlew shadowJar)" >&2
  echo "         then re-run this script." >&2
  exit 1
fi
log "Applying schema with $(basename "$SCHEMA_JAR")..."
java -jar "$SCHEMA_JAR" \
  -url "jdbc:postgresql://127.0.0.1:5432/${DB_NAME}" \
  -user "${DB_USER}" \
  -password "${DB_PASS}" \
  upgrade

log "Done. Database '${DB_NAME}' is ready (role '${DB_USER}', schema applied)."
